services:
  web:
    build: 
      dockerfile: Dockerfile.prod
      context: ./app/web
    container_name: web-prod
    image: web:prod
    restart: unless-stopped
    depends_on:
      - api
    ports:
      - 5000:3000

  api: 
    build: 
      dockerfile: Dockerfile.prod
      context: ./app/api
    container_name: api-prod
    image: api:prod
    restart: unless-stopped
    depends_on: 
      - db
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
    networks:
      - apidb

  db: 
    image: mysql:8.0
    container_name: mysql-prod
    restart: unless-stopped
    ports:
      - 8080:3306
    env_file:
      - ./app/api/.env.production
    volumes: 
      - mysql_prod:/var/lib/mysql
    networks:
      - apidb

volumes:
  mysql_prod:

networks:
    apidb:
        driver: bridge


