services:
  api: 
    build: 
      dockerfile: Dockerfile.dev
      context: ./app
    container_name: api-dev
    image: mnf-api-dev
    restart: unless-stopped
    depends_on: 
      - db
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    volumes: # Volume section does not inherit the build's context defined above.
      - ./app:/app # Bind mounts the host's 'app' directory to the container's 'app' folder (workdir).
      - node_modules_dev_vol:/app/node_modules # Anonymous volume: prevents mounting node_modules and persists them inbetween container runtime.
    networks:
      - apidb

  db: 
    image: mysql:8.0
    container_name: mysql-dev
    restart: unless-stopped
    ports:
      - 8080:3306
    env_file:
      - ./app/.env.development
    volumes: 
      - mysql_dev:/var/lib/mysql
    networks:
      - apidb

volumes:
  mysql_dev:
  node_modules_dev_vol:

networks:
    apidb:
        driver: bridge


