services:
  web:
    build: 
      dockerfile: Dockerfile.dev
      context: ./app/web
    container_name: web-dev
    image: web:dev
    restart: unless-stopped
    depends_on: 
      - api
    ports:
      - 5000:3000
    volumes: # Volume section does not inherit the build's context defined above.
      - ./app/web:/app # Bind mounts the host's 'app' directory to the container's 'app' folder (workdir).
      - web_node_modules_dev_vol:/app/node_modules # Anonymous volume: prevents mounting node_modules and persists them inbetween container runtime.
    networks:
      - webapi
  api: 
    build: 
      dockerfile: Dockerfile.dev
      context: ./app/api
    container_name: api-dev
    image: api:dev
    restart: unless-stopped
    depends_on: 
      - db
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    volumes: # ... ^ 
      - ./app/api:/app # ... ^ 
      - api_node_modules_dev_vol:/app/node_modules # ... ^ 
    networks:
      - apidb
      - webapi

  db: 
    image: mysql:8.0
    container_name: mysql-dev
    restart: unless-stopped
    ports:
      - 8080:3306
    env_file:
      - ./app/api/.env.development
    volumes: 
      - mysql_dev:/var/lib/mysql
    networks:
      - apidb

volumes:
  mysql_dev:
  web_node_modules_dev_vol:
  api_node_modules_dev_vol:

networks:
  apidb:
    driver: bridge
  webapi:
    driver: bridge


