FROM node:20.14.0-alpine

WORKDIR /app

COPY package*.json /app

RUN --mount=type=cache,target=/app/.npm \
    npm set cache /app/.npm && \
    npm ci

COPY . .

RUN npx prisma generate

EXPOSE 3000

CMD npm run build && npm run start