services:
  api: 
    build: 
      dockerfile: Dockerfile.prod
    container_name: api-prod
    image: MNF-api-prod
    restart: unless-stopped
    depends_on: 
      - db
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
    networks:
      - apidb

  db: 
    image: mysql:8.0
    container_name: mysql-prod
    restart: unless-stopped
    ports:
      - 8080:3306
    env_file:
      - .env.production
    volumes: 
      - mysql_prod:/var/lib/mysql
    networks:
      - apidb

volumes:
  mysql_prod:

networks:
    apidb:
        driver: bridge


