services:
  api: 
    build: 
      dockerfile: Dockerfile.dev
    container_name: api-dev
    image: meza-api-dev
    restart: unless-stopped
    depends_on: 
      - db
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app # Bind Mount: mounts the current directory
      - /app/node_modules # Anonymous volume: prevents mounting node_modules and persists them inbetween container runtime
    networks:
      - apidb

  db: 
    image: mysql:8.0
    container_name: mysql-dev
    restart: unless-stopped
    ports:
      - 8080:3306
    env_file:
      - .env.development
    volumes: 
      - mysql_dev:/var/lib/mysql
    networks:
      - apidb

volumes:
  mysql_dev:

networks:
    apidb:
        driver: bridge


