POST http://localhost:5500/carros
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOiI4MTM3YjUyOC00Y2NjLTRmZDctYTI0YS04MTZhZTQ2Y2JkM2IiLCJpYXQiOjE3MDczMTQzNTQsImV4cCI6MTcwNzQwMDc1NH0.rKKV3WYFz2jvPsEGyad03G8IWuptk2gAVkFtmZ1C5rQ

{
    "apelido": "Volks"
}
