POST http://localhost:3000/cadastro
Content-Type: application/json

{
    "email": "eric@gmail.co",
    "senha": "123",
    "confirmacaoSenha": "123"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "eric@gmail.co",
    "senha": "123"
}

###

GET http://localhost:3000/usuarios
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOiJhODg1NGUwMi1mYmU5LTQwYTktOTk2Ny04MzQ2NDgwMDAyNjUiLCJpYXQiOjE3MTg3NTIzMzZ9.1mi31vKpDWf5j5szkhUNaVzk6jLuH3IVRnP74u1kg7U
