POST http://localhost:5500/cadastro
Content-Type: application/json

{
    "email": "eric@gmail.com",
    "senha": "123",
    "confirmacaoSenha": "123"
}

###

POST http://localhost:5500/login
Content-Type: application/json

{
    "email": "eric@gmail.com",
    "senha": "123"
}

###

GET http://localhost:5500/usuarios
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c3VhcmlvSWQiOiIxNTFlMTZlZS1jOWMxLTQxZWUtYWNjZC05NGZjYTJmMWM5MTgiLCJpYXQiOjE3MDk3NjQ1OTIsImV4cCI6MTcwOTg1MDk5Mn0.SZL2ri0-kRQRwnqMTBGmukNfZ1891GFH2RXpE44GKQ4
